kowainik/hit-on

.travis.yml
app/Main.hs
hit-on.cabal
src/Hit.hs
src/Hit/Cli.hs
src/Hit/ColorTerminal.hs
src/HitOn.hs
stack.yaml

[#1] Impl basic CLI

---

hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs

[#2] Implement 'hop' command

---

src/Hit/Cli.hs
src/Hit/Git.hs

[#3] Implement 'fresh' command

---

.travis.yml
hit-on.cabal
src/Hit/Cli.hs
src/Hit/ColorTerminal.hs
src/Hit/Issue.hs
stack.yaml

[#5] Implement issue command

---

src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Shell.hs

[#4] Implement 'new' command

---

src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Shell.hs

Resolves #7
I pushed this code with the implemented command!

[#7] Impl git push command

---

src/Hit/Cli.hs
src/Hit/Git.hs

[#8] Implement 'commit' command

---

src/Hit/Cli.hs
src/Hit/Git.hs

[#9] Implement 'sync' command

---

src/Hit/Cli.hs
src/Hit/Git.hs

[#23] Add 'no-issue' option to 'commit' command

---

src/Hit/Git.hs
src/Hit/Issue.hs

[#6] Add short description to branch

---

src/Hit/Cli.hs
src/Hit/Git.hs

[#11] Implement 'fix' command

---

src/Hit/Issue.hs

[#37] Support OAuth

---

src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Issue.hs

Changed `hit fix` to `hit amend`

---

src/Hit/Cli.hs
src/Hit/Git.hs

@ChShersh Will rectify the duplication in code.

Implemented `hit fix` [WIP]

---

README.md

[#34] Write documentation

---

README.md
src/Hit/Cli.hs
src/Hit/Git.hs

[#51] Add hit clone command

---

src/Hit/ColorTerminal.hs
src/Hit/Issue.hs

[#36] Improve hit issue <n> command output

---

src/Hit/Issue.hs

[#50] Make .git suffix optional

---

README.md

[#47] Specify GITHUB_TOKEN scopes

---

hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Issue.hs

[#43] Add --me option

---

.travis.yml
CHANGELOG.md
README.md
hit-on.cabal
stack.yaml

[#70] Bump up to GHC 8.6.5

---

.gitignore
CHANGELOG.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/ColorTerminal.hs
src/Hit/Git.hs
src/Hit/Git/Status.hs

Resolves #63
Here is how the output looks like:

[#63] Implement 'hit status' command

---

hit-on.cabal
test/Main.hs

Do let me know if anything needs to be changed/corrected/added 😄

[#35] Implement Unit Tests for 'parseOwnerRepo' function

---

hit-on.cabal
src/Hit/Git/Status.hs

Resolves #75
Now it aligned properly :slightly_smiling_face:

[#75] Align count properly

---

CHANGELOG.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git.hs

[#82] Add force flag to hit fix

---

CHANGELOG.md
README.md
src/Hit/Cli.hs
src/Hit/Git.hs

[#85] `hit commit` to guess commit name

---

.travis.yml
CHANGELOG.md
README.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs

Resolves #81
I have `diff-highlight` installed locally and it works for me!

[#81] Implement 'hit diff' command

---

CHANGELOG.md
README.md
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git.hs

[#89] Add [-p|--push] flag to 'hit commit'

---

CHANGELOG.md
README.md

Resolves #69
Makes UI nicer :slightly_smiling_face:

[#69] Set up autocompetion

---

CHANGELOG.md
src/Hit/Cli.hs
src/Hit/Git.hs

[#72] Make `new` command take branch names

---

README.md

[#96] Add table of all supported commands in README

---

.travis.yml

[#49] Configure GitHub releases on Travis CI for OSX

---

src/Hit/ColorTerminal.hs
src/Hit/Git.hs

I modified `yesOrNo` to take a default `Answer` to make it more robust for future usage.

Addresses #112: sets default to `n` in `hit clear` prompt.

---

src/Hit/Cli.hs
src/Hit/Git.hs

Fixes #107
Hlint is giving me some parse errors on some lines in `src/Hit/Git.hs` ( specifically line 63 but it compiles fine so might be something wrong with my hlint config ).

[#107] Add local flag to amend command

---

hit-on.cabal
src/Hit/Formatting.hs
src/Hit/Git/Status.hs
src/Hit/Issue.hs

[#76] Align issues.

---

src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Issue.hs

Still working in progress and not working yet.
I am trying to figure out why it has error while creating new issue
Updated:
#119  looks like will fix the problem
Update 08/10/2019
New issue can be created by following commands
```
hit new --issue "Test hit new --issue command" 
```
or
```
hit new -i "Test hit new --issue command" 
```

[#65] Add issue option to hit new

---

hit-on.cabal
src/Hit/Git.hs
src/Hit/Git/Amend.hs
src/Hit/Git/Clear.hs
src/Hit/Git/Clone.hs
src/Hit/Git/Commit.hs
src/Hit/Git/Common.hs
src/Hit/Git/Current.hs
src/Hit/Git/Diff.hs
src/Hit/Git/Fix.hs
src/Hit/Git/Fresh.hs
src/Hit/Git/Hop.hs
src/Hit/Git/Log.hs
src/Hit/Git/New.hs
src/Hit/Git/Push.hs
src/Hit/Git/Resolve.hs
src/Hit/Git/Stash.hs
src/Hit/Git/Status.hs
src/Hit/Git/Sync.hs
src/Hit/Git/Uncommit.hs
src/Hit/Git/Unstash.hs

[#129] Split Git into smaller modules

---

src/Hit/Git/Log.hs

Resolves #142
It looks like this:

[#142] Implement prettier 'hit log' command

---

CHANGELOG.md
src/Hit/Git/New.hs
src/Hit/Issue.hs

[#15] When new branch for issue created add the user as assignee

---

CHANGELOG.md
src/Hit/Git/Stash.hs

Add `--include-untracked` option to `hit stash` command

---

src/Hit/Formatting.hs
src/Hit/Git/Commit.hs
src/Hit/Git/New.hs
src/Hit/Git/Status.hs

[#156] Take care of RFCs

---

src/Hit/Issue.hs

[#152] Filter out PRs in `hit issue` command

---

CHANGELOG.md
src/Hit/Git/New.hs

[#151] Print issue link when create the issue

---

CHANGELOG.md
src/Hit/Git/Amend.hs

[#154] Add '--date=now' to 'hit ammend'

---

CHANGELOG.md
src/Hit/Git/Status.hs

[#149] Shorter status signs

---

CHANGELOG.md
src/Hit/Git/New.hs

Resolves #148
A tiny one :smile: :cookie:

[#148] Replace dots with hyphens when guessing branch name

---

hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Git/Stash.hs
src/Hit/Git/Wip.hs

[#159] wip commits

---

CHANGELOG.md
src/Hit/Issue.hs

[#155] Notify if there are no open issues

---

src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git/Amend.hs
src/Hit/Git/Clear.hs
src/Hit/Git/Commit.hs
src/Hit/Git/Fix.hs
src/Hit/Git/Push.hs
src/Hit/Git/Sync.hs
src/Hit/Git/Wip.hs

Resolves #136
Also rename `PushBool` to `ForceFlag` (this name sounds a bit more meaningful to me).

[#136] Add `--hard` or `--force` option to the `hit sync` command

---

.headroom.yaml
headroom-templates/haskell.mustache
hit-on.cabal
src/Hit.hs
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Formatting.hs
src/Hit/Git.hs
src/Hit/Git/Amend.hs
src/Hit/Git/Clear.hs
src/Hit/Git/Clone.hs
src/Hit/Git/Commit.hs
src/Hit/Git/Common.hs
src/Hit/Git/Current.hs
src/Hit/Git/Diff.hs
src/Hit/Git/Fix.hs
src/Hit/Git/Fresh.hs
src/Hit/Git/Hop.hs
src/Hit/Git/Log.hs
src/Hit/Git/New.hs
src/Hit/Git/Push.hs
src/Hit/Git/Resolve.hs
src/Hit/Git/Stash.hs
src/Hit/Git/Status.hs
src/Hit/Git/Sync.hs
src/Hit/Git/Uncommit.hs
src/Hit/Git/Unstash.hs
src/Hit/Git/Wip.hs
src/Hit/Issue.hs
src/Hit/Prompt.hs

Resolves #175
I used [headroom](https://github.com/vaclavsvejcar/headroom) to update this information. I also added the config file, so we can reuse it next year (thanks to @vaclavsvejcar config example and for the tool generally :blush:)

[#175] Update header information in the library modules

---

CHANGELOG.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Git/Milestones.hs
src/Hit/GitHub.hs
src/Hit/Issue.hs
test/Main.hs

[#177] `hit milestones` command to get the list of open milestones

---

README.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Git/Commit.hs
src/Hit/Git/Pr.hs
src/Hit/Hub.hs

[#153] Create PRs with a new command/option

---

CHANGELOG.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Git/Branch.hs
src/Hit/Git/Pr.hs
src/Hit/Git/Wip.hs

[#160] hit rename

---

CHANGELOG.md
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git/Branch.hs
src/Hit/Git/Pr.hs
src/Hit/Git/Wip.hs
src/Hit/Issue.hs

[#116] `hit new` without arguments should choose the only assigned issue and create a branch for it

---

CHANGELOG.md
src/Hit/Git/Pr.hs

[#182] Populate labels for the 'hit pr' command

---

CHANGELOG.md
src/Hit/Cli.hs
src/Hit/Git.hs
src/Hit/Git/Clone.hs

[#165] hit fork command

---

hit-on.cabal
src/Hit/Git/Branch.hs
src/Hit/Git/Commit.hs
test/Main.hs
test/Test/Hit/Names.hs

[#163] Add tests: commit msgs. and branch names

---

CHANGELOG.md
src/Hit/Git/Fresh.hs
src/Hit/Prompt.hs

[#109] Do not fail on 'hit fresh' when unsuccessful rebasing

---

CHANGELOG.md
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git/Branch.hs
src/Hit/Issue.hs

[#178] Add  newly created issues to milestones

---

.github/workflows/ci.yml

[#146] Add Windows CI

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
src/Hit/Cli.hs
src/Hit/Git/Branch.hs
src/Hit/Git/Common.hs
src/Hit/Git/Fresh.hs
src/Hit/Git/Hop.hs
src/Hit/Git/Pr.hs
src/Hit/Git/Resolve.hs
src/Hit/Git/Wip.hs
test/Test/Hit/Names.hs

[#201] Switch the default branch to 'main'

---

CHANGELOG.md
README.md
hit-on.cabal
src/Hit/Cli.hs
src/Hit/Core.hs
src/Hit/Git.hs
src/Hit/Git/Tag.hs

[#194] Add 'hit tag' commands
